<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service &middot; Fati Market</title>
    <meta name="description" content="Terms governing the use of the Fati Market mobile application and marketplace.">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root { --brand-900:#0C3021; --brand-800:#10432D; --brand-600:#1A6E49; --brand-500:#22885B; --brand-100:#DCEFE4; --ink-900:#101513; --ink-700:#33403A; --ink-500:#6B7A72; --surface:#fff; --canvas:#F2F5F3; --line:#E4E9E6; --radius:12px; } * { box-sizing:border-box; } body { margin:0; font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif; background:var(--canvas); color:var(--ink-700); line-height:1.65; -webkit-font-smoothing:antialiased; } a { color:var(--brand-600); } a:hover { color:var(--brand-800); } :focus-visible { outline:2px solid var(--brand-500); outline-offset:2px; border-radius:4px; } .masthead { background:var(--brand-900); color:#fff; padding:40px 24px 44px; } .masthead-inner,.page { max-width:940px; margin:0 auto; } .eyebrow { margin:0 0 10px; font-size:12px; font-weight:600; letter-spacing:.12em; text-transform:uppercase; color:var(--brand-100); } .masthead h1 { margin:0 0 12px; color:#fff; font-size:clamp(28px,5vw,40px); line-height:1.15; letter-spacing:-.02em; } .masthead p { margin:0; max-width:62ch; color:rgba(255,255,255,.82); } .date-chip { display:inline-block; margin-top:20px; padding:4px 12px; border:1px solid rgba(255,255,255,.16); border-radius:999px; color:rgba(255,255,255,.9); background:rgba(255,255,255,.1); font-size:13px; } .page { padding:0 24px 72px; } main { max-width:720px; margin:-24px auto 0; padding:8px 40px 40px; border:1px solid var(--line); border-radius:var(--radius); background:var(--surface); box-shadow:0 12px 32px -16px rgba(16,21,19,.18); } section { padding-top:28px; scroll-margin-top:24px; } h2 { margin:0 0 12px; padding-bottom:10px; border-bottom:1px solid var(--line); color:var(--ink-900); font-size:21px; letter-spacing:-.015em; } p,li { font-size:15px; } ul { padding-left:20px; } li { margin-bottom:7px; } strong { color:var(--ink-900); font-weight:600; } .callout { margin:20px 0; padding:14px 18px; border-left:3px solid var(--brand-500); border-radius:0 var(--radius) var(--radius) 0; background:var(--brand-100); } .callout p { margin:0; color:var(--brand-900); } footer { margin-top:40px; padding-top:20px; border-top:1px solid var(--line); font-size:13.5px; color:var(--ink-500); } @media (max-width:640px) { main { padding:8px 22px 32px; } }
    </style>
</head>
<body>
    <header class="masthead"><div class="masthead-inner"><p class="eyebrow">Fati Market</p><h1>Terms of Service</h1><p>These terms explain the rules for using the Fati Market mobile app and student marketplace.</p><span class="date-chip">Effective 13 September 2026</span></div></header>
    <div class="page"><main>
        <section id="acceptance"><h2>1. Acceptance of these terms</h2><p>By creating an account or using Fati Market, you agree to these Terms of Service and our <a href="{{ route('privacy-policy') }}">Privacy Policy</a>. If you do not agree, do not use the app.</p><p>Fati Market is an independent student marketplace project. It is not owned, operated, sponsored, or endorsed by Our Lady of Fatima University or any other school.</p></section>
        <section id="eligibility"><h2>2. Who may use Fati Market</h2><p>Fati Market is intended for university students. You must provide accurate account information and use an email address you are authorized to access. You are responsible for keeping your account and password secure.</p></section>
        <section id="marketplace"><h2>3. Marketplace rules</h2><ul><li>Give accurate, honest descriptions and photos of items you offer.</li><li>Do not list illegal, unsafe, counterfeit, stolen, or prohibited items.</li><li>Do not use the app to harass, threaten, deceive, or impersonate another person.</li><li>Respect agreed pickup arrangements and communicate promptly if you need to change them.</li><li>Do not attempt to bypass the app's order, pickup, or verification process for fraudulent purposes.</li></ul><div class="callout"><p><strong>Users are responsible for their own listings and transactions.</strong> Fati Market helps students organize the marketplace but does not guarantee an item's condition, quality, availability, or suitability.</p></div></section>
        <section id="payments"><h2>4. Payments and pickup</h2><p>Cash and GCash payments are arranged outside the app. Fati Market does not hold funds, process card payments, or act as a bank, escrow service, or payment processor. Never share your GCash PIN, password, one-time code, or other security credentials.</p><p>Payment proofs and reference numbers may be reviewed by administrators to confirm an order. Pickup codes are for confirming collection of the correct order and must not be shared with others.</p></section>
        <section id="content"><h2>5. Your content</h2><p>You remain responsible for the photos, descriptions, messages, and other content you provide. By uploading content to Fati Market, you allow us to display and store it as needed to operate the marketplace, process orders, resolve disputes, and enforce these terms.</p></section>
        <section id="moderation"><h2>6. Administration and enforcement</h2><p>We may remove listings or content, cancel or restrict access, or suspend accounts that violate these terms, create a risk to others, or interfere with the marketplace. We may keep records needed to investigate abuse, settle disputes, or meet legal obligations.</p></section>
        <section id="availability"><h2>7. Availability and liability</h2><p>We aim to keep Fati Market available and accurate, but it is provided on an “as is” and “as available” basis. We do not promise uninterrupted access or that every listing will be error-free. To the extent allowed by law, Fati Market is not liable for losses arising from transactions, communications, payment arrangements, or pickup arrangements between users.</p></section>
        <section id="changes"><h2>8. Changes to the service or terms</h2><p>We may change the app or these terms as the marketplace develops. The effective date at the top of this page shows when the current terms took effect. Continued use after an update means you accept the revised terms.</p></section>
        <section id="contact"><h2>9. Contact</h2><p>For questions, concerns, or reports of misuse, contact us at <a href="mailto:admin@fatimarket.com">admin@fatimarket.com</a>. For information about how we handle personal data, see our <a href="{{ route('privacy-policy') }}">Privacy Policy</a>.</p><footer><p><a href="{{ route('home') }}">Fati Market home</a> &middot; <a href="{{ route('privacy-policy') }}">Privacy Policy</a></p></footer></section>
    </main></div>
</body>
</html>
